### ISSUE TITLE
Where is the evaluator function called in demo.ts?

### ISSUE THREAD

**Issue by luketchang** [oasislabs/ready-layer-two#5]
Had another question about this repo while reading through demo.ts. Looking through the code below, I was having trouble figuring out where/how exactly the evaluator program is called. I looked through the `CompetitionCompleted.subscribe` function and was still struggling with the same confusion and also wasn't sure quite understanding the `spawnSync` function but am assuming one of these has to call the evaluator program. Could you maybe clarify a little bit here? Thanks!

<br>

<img width="518" alt="Screen Shot 2020-09-14 at 2 26 39 PM" src="https://user-images.githubusercontent.com/32170738/93139839-503e2a00-f696-11ea-8a23-84002a7fb6ab.png">

**Comment by nhynes** [comment]
Hey @ltchang2019, another good question. When the competition is completed, the on-chain service emits a `CompetitionCompleted` event, to which the program subscribes. That's the signal that the models are ready to download and test. The top-level demo script invokes the [evaluator program](https://github.com/oasislabs/ready-layer-two/blob/master/app/src/evaluator.ts) with the arguments of the Competition service. The evaluator program pulls down the models and runs the [evaluator python script](https://github.com/oasislabs/ready-layer-two/blob/master/demo/evaluator.py) (built into the "enclaved" [docker image](https://github.com/oasislabs/ready-layer-two/blob/master/demo/Dockerfile#L3)). The python script runs on the data in the "enclave" and posts the results back to the evaluation program, which posts back to the demo script.

Please let me know if you have any follow-up questions!

**Comment by luketchang** [comment]
Ahh ok that makes sense! Thank you again! 🙏
